site_name: Prevented burden comparison

nav:
  - index.md

repo_url: https://github.com/cdcent/cfa-prevented-burden-comparison/
repo_name: cfa-prevented-burden-comparison

theme:
  name: "material"
  icon:
    repo: fontawesome/brands/github

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true
            show_object_full_path: true
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: math
          class: arithmatex
          format:
            !!python/object/apply:pymdownx.arithmatex.arithmatex_fenced_format {
              kwds: { mode: generic, tag: div },
            }

extra_javascript:
  - javascript/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css
